accountProfile/urls.py
from django.urls import path

from accountProfile.views import (
    save_blog,
    unsave_blog,
    get_blogs,

    get_followers_view,
    get_following_view,
    follow_view,
    unfollow_view,

    get_tags_view,
    add_tags_to_profile,
    remove_tags_from_profile,
)

app_name = 'accountProfile'


urlpatterns = [
    path('save_blog/<blog_id>/', save_blog, name='save-blog'),
    path('unsave_blog/<blog_id>/', unsave_blog, name='unsave-blog'),
    path('get_blogs/', get_blogs, name='get-blogs'),
    path('get_blogs/<saved>/', get_blogs, name='get-saved-blogs'),
    path('get_blogs/user/<account_id>/', get_blogs, name='get-user-blogs'),

    path('get_followers/', get_followers_view, name='get-followers'),
    path('get_following/', get_following_view, name='get-following'),
    path('follow/<account_id>/', follow_view, name='follow'),
    path('unfollow/<account_id>/', unfollow_view, name='unfollow'),

    path('get_tags/', get_tags_view, name='get-tags'),
    path('add_tag_to_profile/<tag_id>/', add_tags_to_profile, name='add-tag-to-profile'),
    path('remove_tag_from_profile/<tag_id>/', remove_tags_from_profile, name='remove-tag-from-profile'),
]

blog/urls.py
from django.urls import path

from blog.views import (
    blog_create_view, 
    blog_detail_view, 
    blog_edit_view, 
    blog_delete_view,
    blog_update_view,

    post_add_view,
    post_update_view,
    post_delete_view,
    
    blog_like_view,
    blog_dislike_view,
    comment_view,
    reply_view,
    get_blog_elements_view,

    get_tags_view,
    add_tags_to_blog,
    remove_tags_from_blog,
    publish_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('blog_create', blog_create_view, name='blog-create'),
    path('blog_detail/<blog_id>/', blog_detail_view, name='blog-detail'),
    path('blog_edit/<blog_id>/', blog_edit_view, name='blog-edit'),
    path('blog-delete/<blog_id>/', blog_delete_view, name='blog-delete'),
    path('blog_update/<blog_id>/', blog_update_view, name='blog-update'),

    path('post_add/<blog_id>/', post_add_view, name='post-add'),
    path('post_update/<post_id>/', post_update_view, name='post-update'),
    path('post_delete/<post_id>/', post_delete_view, name='post-delete'),

    path('blog_like/<blog_id>/', blog_like_view, name='like-blog'),
    path('blog_dislike/<blog_id>/', blog_dislike_view, name='dislike-blog'),
    path('blog_comment/<blog_id>/', comment_view, name='comment-blog'),
    path('comment_reply/<comment_id>/', reply_view, name='reply-comment'),
    path('get_blog_elements/<blog_id>/', get_blog_elements_view, name='get-blog-elements'),
    path('get_blog_elements/<blog_id>/<partial>/',get_blog_elements_view, name='get-blog-elements'),

    path('get_tags/<blog_id>/', get_tags_view, name='get-tags'),
    path('add_tag_to_blog/<blog_id>/<tag_id>/', add_tags_to_blog, name='add-tag-to-blog'),
    path('remove_tag_from-blog/<blog_id>/<tag_id>/', remove_tags_from_blog, name='remove-tag-from-blog'),
    path('publish_blog/<blog_id>/', publish_blog_view, name='publish-blog'),
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from blogs.views import home


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    
    path('', include('account.urls', namespace='account')),
    path('api/', include('account.api.urls', namespace='account_api')),

    path('', include('accountProfile.urls', namespace='accountProfile')),

    path('', include('blog.urls', namespace='blog')),
]

handler404 = 'blogs.views.page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms

from blog.models import Blog, Post, Comment, Reply


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['heading', 'description']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']

blog/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib import messages

import datetime

from blog.models import Blog, Post, Comment ,Reply, Tag
from blog.forms import BlogForm, PostForm


def get_blog_by_id(id):
    try:
        blog = Blog.objects.get(id=id)
        return blog
    except Blog.DoesNotExist:
        return None


def get_post_by_id(id):
    try:
        post = Post.objects.get(id=id)
        return post
    except Post.DoesNotExist:
        return None


def get_comment_by_id(id):
    try:
        comment = Comment.objects.get(id=id)
        return comment
    except Comment.DoesNotExist:
        return None


def get_tag_by_id(id):
    try:
        tag = Tag.objects.get(id=id)
        return tag
    except Tag.DoesNotExist:
        return None


def blog_create_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(request, 'You must login to create or update your blogs.')
        return redirect('account:login')

    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = user
            blog.save()
            form.save_m2m()

            messages.success(request, f'Blog created successfully.')
            return redirect('blog:blog-detail', blog_id = blog.id)
        else:
            context['form'] = form

    if request.method == 'GET':
        form = BlogForm()
        context['form'] = form
    return render(request, 'blog/blog_add.html', context)


def blog_detail_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(
            request, 'You must login to view blogs or posts.')
        return redirect('account:login')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        messages.warning(request, 'Sorry!, blog not available.')
        return redirect('home')

    context['blog'] = blog
    return render(request, 'blog/blog_detail.html', context)


def blog_edit_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(
            request, 'You must login to create or update your blogs or posts.')
        return redirect('account:login')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        messages.warning(request, 'Sorry!, blog not available.')
        return redirect('home')

    context['blog'] = blog

    if not blog.user == request.user:
        messages.warning(request, 'You cannot edit other persons blog.')
        return redirect('home')

    return render(request, 'blog/blog_edit.html', context)


def blog_update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to create or update your blogs or posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, blog not available.</div>')

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons blog.</div>')

    if request.method == "GET":
        form = BlogForm(instance=blog)
        context['blog'] = blog
        context['form'] = form
        return render(request, 'blog/snippets/blog_form.html', context)

    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            context['blog'] = blog
            return render(request, 'blog/snippets/blog.html', context)
        else:
            context['form'] = form
            context['blog'] = blog
            return render(request, 'blog/snippets/blog_form.html', context)


def blog_delete_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to delete your blogs or posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, blog not available.</div>')

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot delete other persons blog.</div>')

    if request.method == 'POST':
        blog.delete()
        messages.success(request, 'Blog deleted successfully.')
        return redirect('home')

    if request.method == 'GET':
        context['blog'] = blog

    return render(request, 'blog/blog_delete.html', context)


def post_add_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to add posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons blog.</div>')

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.blog = blog
            post.save()
            context['post'] = post
            return render(request, 'blog/snippets/post.html', context)
        else:
            context['form'] = form
            context['post'] = {'id': 'id-temp'} 
            return render(request, 'blog/snippets/post_add_form.html', context)

    if request.method == 'GET':
        form = PostForm()
        context['form'] = form
        context['blog'] = blog
        context['post'] = {'id': 'id-temp'}
    return render(request, 'blog/snippets/post_add_form.html', context)


def post_update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to create or update your blogs or posts.</div>')

    post_id = kwargs.get('post_id')
    post = get_post_by_id(post_id)

    if not post:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, post not available.</div>')

    if not post.blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons post.</div>')

    if request.method == "GET":
        form = PostForm(instance=post)
        context['post'] = post
        context['form'] = form
        return render(request, 'blog/snippets/post_form.html', context)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            context['post'] = post
            return render(request, 'blog/snippets/post.html', context)
        else:
            context['post'] = post
            context['form'] = form
            return render(request, 'blog/snippets/post_form.html', context)


def post_delete_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to delete your blogs or posts.</div>')

    post_id = kwargs.get('post_id')
    post = get_post_by_id(post_id)

    if not post:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, post not available.</div>')

    if not post.blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot delete other persons post.</div>')

    post.delete()
    return HttpResponse()


def blog_like_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You cannot like a post unless you Login.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if blog:
        blog.like(user)

        context['blog'] = blog
    else:
        return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/blog_options.html', context)


def blog_dislike_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You cannot dislike a post unless you Login.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if blog:
        blog.dislike(user)

        context['blog'] = blog
    else:
        return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/blog_options.html', context)


def comment_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to comment on post.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if request.method == 'POST':
        body = request.POST.get('comment-input', '')
        if blog:
            comment = Comment.objects.create(blog=blog, user=request.user, body=body)
            context['comment'] = comment
        else:
            return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/comment.html', context)


def reply_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to reply on comment.</div>')

    context = {}
    comment_id = kwargs.get('comment_id')
    comment = get_comment_by_id(comment_id)

    if request.method == 'POST':

blogs/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 

from blog.models import Blog

def home(request, *args, **kwargs):
    context = {}

    blog_objects = Blog.objects.filter(status='1')

    paginator = Paginator(blog_objects, 5)
    page = request.GET.get('page')

    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    context ['blogs'] = blogs
    return render(request, 'home.html', context)

def page_not_found_view(request, *args, **kwargs):
    return render(request, '404.html', status=404)

blog/templates/blog/snippets/blog.html
<div id="id-blog-{{blog.id}}" class="d-flex flex-column my-2 p-2">
    <p class="m-0"><strong>{{ blog.heading }}</strong></p>
    <p class="m-0">{{ blog.description }}</p>

    <div class="flex mb-2 mt-4 pb-2 border-bottom">
        <button 
            class="btn btn-outline-info" 
            hx-trigger="click" 
            hx-get="{% url 'blog:blog-update' blog_id=blog.id %}"
            hx-target="#id-blog-{{blog.id}}" 
            hx-swap="outerHTML"
        >
            Update
        </button>
        <a href="{% url 'blog:blog-delete' blog_id=blog.id %}" class="btn btn-outline-danger">Delete</a>
    </div>
</div>

blog/templates/blog/snippets/blog_elements.html
{% include 'blog/snippets/blog_options.html' %}

<div class="d-flex border-top p-2 border-bottom">
    <form 
        id="comment-form" 
        class="inline-form" 
        hx-post="{% url 'blog:comment-blog' blog_id=blog.id %}"
        hx-target="#id-blog-comments" 
        hx-swap="afterbegin"
    >
        <input class="comment-input" name="comment-input" type="text" placeholder="write your comment...">
    </form>
</div>

<div id="id-blog-comments" class="d-flex flex-column flex-start p-2">
    {% for comment in blog.comments.all %}
    {% include 'blog/snippets/comment.html' %}
    {% endfor %}
</div>

blog/templates/blog/snippets/blog_form.html
<div id="id-blog-{{blog.id}}" class="d-flex flex-column my-2 p-2 border-bottom">
    <form
        hx-post="{% url 'blog:blog-update' blog_id=blog.id %}"
        hx-target="#id-blog-{{blog.id}}"
        hx-swap="outerHTML"
    >
        {% if form %}
        {% include 'snippets/form.html' %}
        {% endif %}

        <button class="btn btn-outline-info mt-2">Update</button>
    </form>
</div>

blog/templates/blog/snippets/blog_options.html
{% load temptags %}
<div id="id-blog-options-{{blog.id}}" class="d-flex justify-content-between border-top p-2">
    <div class="d-flex" id="like-container">
        <span class="btn" id="like-count">{{ blog|getLikeCount }}</span>
        {% if request.user in blog.likes.all %}
        <button 
            id="like-btn"
            class="btn bg-none {% if not request.user.is_authenticated %} disabled {% endif %}"
            hx-get="{% url 'blog:like-blog' blog_id=blog.id %}"
            hx-trigger="click" 
            hx-target="#id-blog-options-{{blog.id}}"
            hx-swap="outerHTML">
            Liked
        </button>
        {% else %}
        <button 
            id="like-btn" 
            class="btn bg-none {% if not request.user.is_authenticated %} disabled {% endif %}" 
            hx-get="{% url 'blog:like-blog' blog_id=blog.id %}" 
            hx-trigger="click"
            hx-target="#id-blog-options-{{blog.id}}" 
            hx-swap="outerHTML">
            Like
        </button>
        {% endif %}
    </div>

    <div class="d-flex" id="like-container">
        <span class="btn" id="dislike-count">{{ blog|getDislikeCount }}</span>
        {% if request.user in blog.dislikes.all %}
        <button 
            id="dislike-btn" 
            class="btn bg-none {% if not request.user.is_authenticated %} disabled {% endif %}" 
            hx-get="{% url 'blog:dislike-blog' blog_id=blog.id %}" 
            hx-trigger="click"
            hx-target="#id-blog-options-{{blog.id}}" 
            hx-swap="outerHTML">
            Disliked
        </button>
        {% else %}
        <button 
            id="dislike-btn" 
            class="btn bg-none {% if not request.user.is_authenticated %} disabled {% endif %}" 
            hx-get="{% url 'blog:dislike-blog' blog_id=blog.id %}" 
            hx-trigger="click"
            hx-target="#id-blog-options-{{blog.id}}" 
            hx-swap="outerHTML">
            Dislike
        </button>
        {% endif %}
    </div>

    <div>
        {% if blog in request.user.profile.saved_blogs.all %}
        <button 
            id="dislike-btn" 
            class="btn bg-none {% if not request.user.is_authenticated %} disabled {% endif %}" 
            hx-get="{% url 'accountProfile:unsave-blog' blog_id=blog.id %}" 
            hx-trigger="click"
            hx-target="#id-blog-options-{{blog.id}}" 
            hx-swap="outerHTML">
            Saved
        </button>
        {% else %}
        <button 
            id="dislike-btn" 
            class="btn bg-none {% if not request.user.is_authenticated %} disabled {% endif %}" 
            hx-get="{% url 'accountProfile:save-blog' blog_id=blog.id %}" 
            hx-trigger="click"
            hx-target="#id-blog-options-{{blog.id}}" 
            hx-swap="outerHTML">
            Save
        </button>
        {% endif %}
    </div>
    
</div>

blog/templates/blog/snippets/comment.html
<div>
    <div class="comment-div">
        <img src="{{ comment.user.display_pic.url }}" alt="Profile Pic" class="thumbnail">
        <div class="comment-body">
            <p class="m-0 text-bold">{{ comment.user.username }}</p>
            <p class="m-0">{{ comment.body }}</p>
        </div>
    </div>

    {% if request.user.is_authenticated %}
    <div id="id-comment-options">
        <button href="#" class="btn reply-btn bg-none" id="id-reply-btn-{{ comment.id }}" onclick="showReplyForm('{{ comment.id }}')">reply</button>
        <form
            id="id-reply-form-{{comment.id}}" 
            class="d-none"
            class="inline-form"
            hx-post="{% url 'blog:reply-comment' comment_id=comment.id %}"
            hx-target="#id-replies-{{comment.id}}"
            hx-swap="beforeend"
            >
            <input class="reply-input" name="reply-input" type="text" placeholder="write your reply...">
        </form>
    </div>
{% endif %}

    <div id="id-replies-{{comment.id}}">
        {% for reply in comment.replies.all %}
        {% include "blog/snippets/reply.html" %}
        {% endfor %}
    </div> 
</div>

blog/templates/blog/snippets/post.html
<div id="id-post-{{post.id}}" class="d-flex flex-column my-2 p-2">
    <p>{{ post.content }}</p>
    {% if post.image %}
    <img class="display-img rounded my-2" src="{{ post.image.url }}">
    {% endif %}

    <div class="flex mt-4 mb-2 pb-2 border-bottom">
        <button 
            class="btn btn-outline-info"
            hx-trigger="click" 
            hx-get="{% url 'blog:post-update' post_id=post.id %}"
            hx-target="#id-post-{{post.id}}" 
            hx-swap="outerHTML"
        >
            Update
        </button>
        <button 
            class="btn btn-outline-danger"
            hx-trigger="click" 
            hx-get="{% url 'blog:post-delete' post_id=post.id %}"
            hx-target="#id-post-{{post.id}}" 
            hx-swap="outerHTML"
        >
            Delete
        </button>
    </div>
</div>

blog/templates/blog/snippets/post_add_form.html
<div id="id-post-{{post.id}}" class="d-flex flex-column my-2 border-bottom">
    <form 
        hx-encoding="multipart/form-data" 
        hx-post="{% url 'blog:post-add' blog_id=blog.id %}"
        hx-target="#id-post-{{post.id}}" 
        hx-swap="outerHTML"
    >

        {% if form %}
        {% for error in form.non_field.errors %}
        <small class="text-danger">{{ error }}</small>
        {% endfor %}
        {% for field in form.hidden_fields %}
        {{ field }}
        {% for error in field.errors %}
        <small class="text-danger">{{ error }}</small>
        {% endfor %}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="form-element">
            {% if field.field.widget.input_type != "checkbox" %}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {% else %}
            {{ field }}
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {% endif %}
            {% if field.help_text %}
            <div class="ml-2 mb-0"><small>{{ field.help_text }}</small></div>
            {% endif %}
            {% for error in field.errors %}
            <small class="text-danger">{{ error }}</small>
            {% endfor %}
        </div>
        {% endfor %}
        {% endif %}

        <div class="mt-2 pb-2 border-top">
            <button class="btn btn-outline-info mt-2">Add</button>
        </div>
    </form>
</div>

blog/templates/blog/snippets/post_form.html
<div id="id-post-{{post.id}}" class="d-flex flex-column my-2 border-bottom">
    <form 
        hx-encoding="multipart/form-data"
        hx-post="{% url 'blog:post-update' post_id=post.id %}" 
        hx-target="#id-post-{{post.id}}" 
        hx-swap="outerHTML"
    >

        {% if form %}
            {% for error in form.non_field.errors %}
            <small class="text-danger">{{ error }}</small>
            {% endfor %}
            {% for field in form.hidden_fields %}
            {{ field }}
            {% for error in field.errors %}
            <small class="text-danger">{{ error }}</small>
            {% endfor %}
            {% endfor %}
            {% for field in form.visible_fields %}
            <div class="form-element">
                {% if field.field.widget.input_type != "checkbox" %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field }}
                {% else %}
                {{ field }}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% endif %}
                {% if field.help_text %}
                <div class="ml-2 mb-0"><small>{{ field.help_text }}</small></div>
                {% endif %}
                {% for error in field.errors %}
                <small class="text-danger">{{ error }}</small>
                {% endfor %}
            </div>
            {% endfor %}
        {% endif %}

        <div class="mt-2 pb-2 border-top">
            <button class="btn btn-outline-info mt-2">Update</button>
        </div>
    </form>
</div>

blog/templates/blog/snippets/reply.html
<div class="comment-div ml-5">
    <img src="{{ reply.user.display_pic.url }}" alt="Profile Pic" class="thumbnail">
    <div class="comment-body">
        <p class="m-0 text-bold">{{ reply.user.username }}</p>
        <p class="m-0">{{ reply.body }}</p>
    </div>
</div>

blog/templates/blog/snippets/tags.html
    <div id="id-tag-container" class="d-flex flex-wrap p-2 border-bottom">
        {% if tags %}
        {% for tag in tags %}
            {% if tag in blog.tags.all %}
            <div class="btn-info px-2 my-1 mx-2 rounded">
                {{tag}} 
                <span 
                    class="btn px-0"
                    hx-trigger="click"
                    hx-get="{% url 'blog:remove-tag-from-blog' blog_id=blog.id tag_id=tag.id %}"
                    hx-target="#id-tag-container"
                    hx-swap="outerHTML"
                    >
                    -
                </span>
            </div>
            {% else %}
            <div class="btn-info px-2 my-1 mx-2 rounded">
                {{tag}} 
                <span 
                class="btn px-0"
                hx-trigger="click"
                hx-get="{% url 'blog:add-tag-to-blog' blog_id=blog.id tag_id=tag.id %}"
                hx-target="#id-tag-container"
                hx-swap="outerHTML"
                >
                +
            </span>
            </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <p class="m-0">No tags available</p>
        {% endif %}
    </div>