blog/urls.py
from django.urls import path

from blog.views import (
    blog_create_view, 
    blog_detail_view, 
    blog_edit_view, 
    blog_delete_view,
    blog_update_view,

    post_add_view,
    post_update_view,
    post_delete_view,
    
    blog_like_view,
    blog_dislike_view,
    comment_view,
    reply_view,
    get_blog_elements_view,

    get_tags_view,
    add_tags_to_blog,
    remove_tags_from_blog,
    publish_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('blog_create', blog_create_view, name='blog-create'),
    path('blog_detail/<blog_id>/', blog_detail_view, name='blog-detail'),
    path('blog_edit/<blog_id>/', blog_edit_view, name='blog-edit'),
    path('blog-delete/<blog_id>/', blog_delete_view, name='blog-delete'),
    path('blog_update/<blog_id>/', blog_update_view, name='blog-update'),

    path('post_add/<blog_id>/', post_add_view, name='post-add'),
    path('post_update/<post_id>/', post_update_view, name='post-update'),
    path('post_delete/<post_id>/', post_delete_view, name='post-delete'),

    path('blog_like/<blog_id>/', blog_like_view, name='like-blog'),
    path('blog_dislike/<blog_id>/', blog_dislike_view, name='dislike-blog'),
    path('blog_comment/<blog_id>/', comment_view, name='comment-blog'),
    path('comment_reply/<comment_id>/', reply_view, name='reply-comment'),
    path('get_blog_elements/<blog_id>/', get_blog_elements_view, name='get-blog-elements'),
    path('get_blog_elements/<blog_id>/<partial>/',get_blog_elements_view, name='get-blog-elements'),

    path('get_tags/<blog_id>/', get_tags_view, name='get-tags'),
    path('add_tag_to_blog/<blog_id>/<tag_id>/', add_tags_to_blog, name='add-tag-to-blog'),
    path('remove_tag_from-blog/<blog_id>/<tag_id>/', remove_tags_from_blog, name='remove-tag-from-blog'),
    path('publish_blog/<blog_id>/', publish_blog_view, name='publish-blog'),
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from blogs.views import home


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    
    path('', include('account.urls', namespace='account')),
    path('api/', include('account.api.urls', namespace='account_api')),

    path('', include('accountProfile.urls', namespace='accountProfile')),

    path('', include('blog.urls', namespace='blog')),
]

handler404 = 'blogs.views.page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms

from blog.models import Blog, Post, Comment, Reply


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['heading', 'description']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']

blog/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib import messages

import datetime

from blog.models import Blog, Post, Comment ,Reply, Tag
from blog.forms import BlogForm, PostForm


def get_blog_by_id(id):
    try:
        blog = Blog.objects.get(id=id)
        return blog
    except Blog.DoesNotExist:
        return None


def get_post_by_id(id):
    try:
        post = Post.objects.get(id=id)
        return post
    except Post.DoesNotExist:
        return None


def get_comment_by_id(id):
    try:
        comment = Comment.objects.get(id=id)
        return comment
    except Comment.DoesNotExist:
        return None


def get_tag_by_id(id):
    try:
        tag = Tag.objects.get(id=id)
        return tag
    except Tag.DoesNotExist:
        return None


def blog_create_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(request, 'You must login to create or update your blogs.')
        return redirect('account:login')

    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = user
            blog.save()
            form.save_m2m()

            messages.success(request, f'Blog created successfully.')
            return redirect('blog:blog-detail', blog_id = blog.id)
        else:
            context['form'] = form

    if request.method == 'GET':
        form = BlogForm()
        context['form'] = form
    return render(request, 'blog/blog_add.html', context)


def blog_detail_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(
            request, 'You must login to view blogs or posts.')
        return redirect('account:login')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        messages.warning(request, 'Sorry!, blog not available.')
        return redirect('home')

    context['blog'] = blog
    return render(request, 'blog/blog_detail.html', context)


def blog_edit_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(
            request, 'You must login to create or update your blogs or posts.')
        return redirect('account:login')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        messages.warning(request, 'Sorry!, blog not available.')
        return redirect('home')

    context['blog'] = blog

    if not blog.user == request.user:
        messages.warning(request, 'You cannot edit other persons blog.')
        return redirect('home')

    return render(request, 'blog/blog_edit.html', context)


def blog_update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to create or update your blogs or posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, blog not available.</div>')

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons blog.</div>')

    if request.method == "GET":
        form = BlogForm(instance=blog)
        context['blog'] = blog
        context['form'] = form
        return render(request, 'blog/snippets/blog_form.html', context)

    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            context['blog'] = blog
            return render(request, 'blog/snippets/blog.html', context)
        else:
            context['form'] = form
            context['blog'] = blog
            return render(request, 'blog/snippets/blog_form.html', context)


def blog_delete_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to delete your blogs or posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, blog not available.</div>')

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot delete other persons blog.</div>')

    if request.method == 'POST':
        blog.delete()
        messages.success(request, 'Blog deleted successfully.')
        return redirect('home')

    if request.method == 'GET':
        context['blog'] = blog

    return render(request, 'blog/blog_delete.html', context)


def post_add_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to add posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons blog.</div>')

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.blog = blog
            post.save()
            context['post'] = post
            return render(request, 'blog/snippets/post.html', context)
        else:
            context['form'] = form
            context['post'] = {'id': 'id-temp'} 
            return render(request, 'blog/snippets/post_add_form.html', context)

    if request.method == 'GET':
        form = PostForm()
        context['form'] = form
        context['blog'] = blog
        context['post'] = {'id': 'id-temp'}
    return render(request, 'blog/snippets/post_add_form.html', context)


def post_update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to create or update your blogs or posts.</div>')

    post_id = kwargs.get('post_id')
    post = get_post_by_id(post_id)

    if not post:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, post not available.</div>')

    if not post.blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons post.</div>')

    if request.method == "GET":
        form = PostForm(instance=post)
        context['post'] = post
        context['form'] = form
        return render(request, 'blog/snippets/post_form.html', context)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            context['post'] = post
            return render(request, 'blog/snippets/post.html', context)
        else:
            context['post'] = post
            context['form'] = form
            return render(request, 'blog/snippets/post_form.html', context)


def post_delete_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to delete your blogs or posts.</div>')

    post_id = kwargs.get('post_id')
    post = get_post_by_id(post_id)

    if not post:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, post not available.</div>')

    if not post.blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot delete other persons post.</div>')

    post.delete()
    return HttpResponse()


def blog_like_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You cannot like a post unless you Login.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if blog:
        blog.like(user)

        context['blog'] = blog
    else:
        return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/blog_options.html', context)


def blog_dislike_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You cannot dislike a post unless you Login.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if blog:
        blog.dislike(user)

        context['blog'] = blog
    else:
        return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/blog_options.html', context)


def comment_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to comment on post.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if request.method == 'POST':
        body = request.POST.get('comment-input', '')
        if blog:
            comment = Comment.objects.create(blog=blog, user=request.user, body=body)
            context['comment'] = comment
        else:
            return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/comment.html', context)


def reply_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to reply on comment.</div>')

    context = {}
    comment_id = kwargs.get('comment_id')
    comment = get_comment_by_id(comment_id)

    if request.method == 'POST':

blogs/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 

from blog.models import Blog

def home(request, *args, **kwargs):
    context = {}

    blog_objects = Blog.objects.filter(status='1')

    paginator = Paginator(blog_objects, 5)
    page = request.GET.get('page')

    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    context ['blogs'] = blogs
    return render(request, 'home.html', context)

def page_not_found_view(request, *args, **kwargs):
    return render(request, '404.html', status=404)

blog/templates/blog/blog_add.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-section">
    <form method="post">
        {% csrf_token %}
        <legend class="border-bottom mb-2">Add Blog</legend>
        {% include 'snippets/form.html' %}
        <div class="flex">
            <button type="submit" class="btn btn-outline-info">Add</button>
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/blog/blog_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-section">
    <p class="border-bottom py-2">Are you sure you wanted to delete this blog. <strong>{{ blog.heading }}</strong></p>
    <div class="d-flex">
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
        <a href="{% url 'blog:blog-detail' blog_id=blog.id %}" class="btn btn-info mx-2">Cancel</a>
    </div>
</div>
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-section">
{% if blog %}

<div id="id-blog-header" class="d-flex justify-content-between border-bottom p-1">
    <p class="heading m-0">Blog</p>
    <div>
        {% if blog.user == request.user %}
        <a href="{% url 'blog:blog-edit' blog_id=blog.id %}" class="btn btn-outline-info">Edit</a>
        <a href="{% url 'blog:blog-delete' blog_id=blog.id %}" class="btn btn-outline-danger">Delete</a>
        {% endif %}
    </div>
</div>

<div id="id-blog-container">
    <div id="id-blog-{{blog.id}}" class="d-flex flex-column my-2 p-2">
        <p class="m-0"><strong>{{ blog.heading }}</strong></p>
        <p class="m-0">{{ blog.description }}</p>
    </div>

    <div id="id-post-container">
        {% for post in blog.posts.all %}    
        <div id="id-post-{{post.id}}" class="d-flex flex-column my-2 p-2">
            {% if post.image %}
            <img class="display-img rounded my-2" src="{{ post.image.url }}">
            {% endif %}
            {{ post.content }}
        </div>
        {% endfor %}
    </div>
</div>

<div 
    id="id-blog-details"
    hx-trigger="every 30s"
    hx-get="{% url 'blog:get-blog-elements' blog_id=blog.id %}"
    hx-target="#id-blog-details"
    hx-swap="innerHTML"
    >
    {% include 'blog/snippets/blog_elements.html' %}
</div>

{% else %}
<p class="p-4">Blog not found.</p>
{% endif %}
</div>

<script>
    document.body.addEventListener("htmx:configRequest", (event) => {
        event.detail.headers["X-CSRFToken"] = "{{ csrf_token }}"
    })

    document.body.addEventListener("htmx:afterRequest", (event) => {
        document.querySelector("input.comment-input").value = ""
        let replyInputs = document.querySelectorAll("input.reply-input")
        replyInputs.forEach((reply) => {
            reply.value = ""
        })
    })

    const showReplyForm = (commentId) => {
        event.preventDefault()
        document.getElementById(`id-reply-btn-${commentId}`).classList.add("d-none")
        document.getElementById(`id-reply-form-${commentId}`).classList.remove("d-none")
    }
</script>
{% endblock content %}

blog/templates/blog/blog_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-section">
    {% if blog %}

    <div id="id-blog-header" class="d-flex flex-wrap justify-content-between border-bottom p-1">
        <p class="heading m-0">Blog</p>
        <div class="d-flex flex-wrap py-1 ml-2">
            {% if blog.user == request.user %}
            {% if not blog.is_published %}
            <button 
                class="btn btn-outline-info mx-1 mt-1" 
                hx-trigger="click" 
                hx-get="{% url 'blog:publish-blog' blog_id=blog.id %}"
                hx-target="this"
                hx-swap="outerHTML"
            >
                Publish
            </button>
            {% endif %}
            <button
                id="id_tag_btn"
                class="btn btn-outline-info mx-1 mt-1" 
                hx-trigger="click" 
                hx-get="{% url 'blog:get-tags' blog_id=blog.id %}"
                hx-target="#id-blog-container" 
                hx-swap="afterbegin"
            >
                Add tags
            </button>
            <button  
                class="btn btn-outline-info mx-1 mt-1"
                hx-trigger="click" 
                hx-get="{% url 'blog:post-add' blog_id=blog.id %}"
                hx-target="#id-post-container" 
                hx-swap="beforeend"
            >
                Add New Post
            </button>
            {% endif %}
        </div>
    </div>

    <div id="id-blog-container">
        {% include 'blog/snippets/blog.html' %}

        <div id="id-post-container">
        {% for post in blog.posts.all %}
            {% include 'blog/snippets/post.html' %}
        {% endfor %}
        </div>
    </div>

    {% else %}
    <p class="p-4">Blog not found.</p>
    {% endif %}
</div>

<script>
    document.body.addEventListener("htmx:configRequest", (event) => {
        event.detail.headers["X-CSRFToken"] = "{{ csrf_token }}"
    })

    document.getElementById('id_tag_btn').addEventListener('click', async (e) => {
        e.preventDefault()
        await delay(1000)
        document.getElementById('id_tag_btn').remove()
    })

    function delay(milliseconds) {
        return new Promise(resolve => {
            setTimeout(resolve, milliseconds);
        });
    }
</script>
{% endblock content %}