account/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,

    PasswordChangeView,
    PasswordChangeDoneView,
)

from account.views import (
    login_view,
    logout_view,
    register_view,
    account_verify_view,
    account_view,
    account_update_view,
    account_search_view,
    account_deactivate_view,
    account_delete_view
)


app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('account_verify/<uidb64>/<token>/',
         account_verify_view, name='account-verify'),

    path('account/<user_id>/', account_view, name='account'),
    path('account_update/', account_update_view, name='account-update'),
    path('account_search/', account_search_view, name='account-search'),
    path('account_deactivate/', account_deactivate_view, name='account-deactivate'),
    path('account_delete/', account_delete_view, name='account-delete'),


    path('password_reset/', PasswordResetView.as_view(
        template_name='account/password/password_reset.html',
        email_template_name='account/password/password_reset_email.html',
        success_url=reverse_lazy('account:password-reset-done')),
        name='password-reset'
    ),
    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name='account/password/password_reset_done.html'),
        name='password-reset-done'
    ),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='account/password/password_reset_confirm.html',
        success_url=reverse_lazy('account:password-reset-complete')),
        name='password-reset-confirm'
    ),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(
        template_name='account/password/password_reset_complete.html'),
        name='password-reset-complete'
    ),

    path('password_change/', PasswordChangeView.as_view(
        template_name='account/password/password_change.html',
        success_url=reverse_lazy('account:password-change-done')),
        name='password-change'
    ),
    path('password_change_done/', PasswordChangeDoneView.as_view(
        template_name='account/password/password_change_done.html'),
        name='password-change-done'
    ),
]

accountProfile/urls.py
from django.urls import path

from accountProfile.views import (
    save_blog,
    unsave_blog,
    get_blogs,

    get_followers_view,
    get_following_view,
    follow_view,
    unfollow_view,

    get_tags_view,
    add_tags_to_profile,
    remove_tags_from_profile,
)

app_name = 'accountProfile'


urlpatterns = [
    path('save_blog/<blog_id>/', save_blog, name='save-blog'),
    path('unsave_blog/<blog_id>/', unsave_blog, name='unsave-blog'),
    path('get_blogs/', get_blogs, name='get-blogs'),
    path('get_blogs/<saved>/', get_blogs, name='get-saved-blogs'),
    path('get_blogs/user/<account_id>/', get_blogs, name='get-user-blogs'),

    path('get_followers/', get_followers_view, name='get-followers'),
    path('get_following/', get_following_view, name='get-following'),
    path('follow/<account_id>/', follow_view, name='follow'),
    path('unfollow/<account_id>/', unfollow_view, name='unfollow'),

    path('get_tags/', get_tags_view, name='get-tags'),
    path('add_tag_to_profile/<tag_id>/', add_tags_to_profile, name='add-tag-to-profile'),
    path('remove_tag_from_profile/<tag_id>/', remove_tags_from_profile, name='remove-tag-from-profile'),
]

blog/urls.py
from django.urls import path

from blog.views import (
    blog_create_view, 
    blog_detail_view, 
    blog_edit_view, 
    blog_delete_view,
    blog_update_view,

    post_add_view,
    post_update_view,
    post_delete_view,
    
    blog_like_view,
    blog_dislike_view,
    comment_view,
    reply_view,
    get_blog_elements_view,

    get_tags_view,
    add_tags_to_blog,
    remove_tags_from_blog,
    publish_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('blog_create', blog_create_view, name='blog-create'),
    path('blog_detail/<blog_id>/', blog_detail_view, name='blog-detail'),
    path('blog_edit/<blog_id>/', blog_edit_view, name='blog-edit'),
    path('blog-delete/<blog_id>/', blog_delete_view, name='blog-delete'),
    path('blog_update/<blog_id>/', blog_update_view, name='blog-update'),

    path('post_add/<blog_id>/', post_add_view, name='post-add'),
    path('post_update/<post_id>/', post_update_view, name='post-update'),
    path('post_delete/<post_id>/', post_delete_view, name='post-delete'),

    path('blog_like/<blog_id>/', blog_like_view, name='like-blog'),
    path('blog_dislike/<blog_id>/', blog_dislike_view, name='dislike-blog'),
    path('blog_comment/<blog_id>/', comment_view, name='comment-blog'),
    path('comment_reply/<comment_id>/', reply_view, name='reply-comment'),
    path('get_blog_elements/<blog_id>/', get_blog_elements_view, name='get-blog-elements'),
    path('get_blog_elements/<blog_id>/<partial>/',get_blog_elements_view, name='get-blog-elements'),

    path('get_tags/<blog_id>/', get_tags_view, name='get-tags'),
    path('add_tag_to_blog/<blog_id>/<tag_id>/', add_tags_to_blog, name='add-tag-to-blog'),
    path('remove_tag_from-blog/<blog_id>/<tag_id>/', remove_tags_from_blog, name='remove-tag-from-blog'),
    path('publish_blog/<blog_id>/', publish_blog_view, name='publish-blog'),
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from blogs.views import home


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    
    path('', include('account.urls', namespace='account')),
    path('api/', include('account.api.urls', namespace='account_api')),

    path('', include('accountProfile.urls', namespace='accountProfile')),

    path('', include('blog.urls', namespace='blog')),
]

handler404 = 'blogs.views.page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms

from blog.models import Blog, Post, Comment, Reply


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['heading', 'description']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']

blog/views.py
from django.shortcuts import redirect, render, HttpResponse
from django.contrib import messages

import datetime

from blog.models import Blog, Post, Comment ,Reply, Tag
from blog.forms import BlogForm, PostForm


def get_blog_by_id(id):
    try:
        blog = Blog.objects.get(id=id)
        return blog
    except Blog.DoesNotExist:
        return None


def get_post_by_id(id):
    try:
        post = Post.objects.get(id=id)
        return post
    except Post.DoesNotExist:
        return None


def get_comment_by_id(id):
    try:
        comment = Comment.objects.get(id=id)
        return comment
    except Comment.DoesNotExist:
        return None


def get_tag_by_id(id):
    try:
        tag = Tag.objects.get(id=id)
        return tag
    except Tag.DoesNotExist:
        return None


def blog_create_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(request, 'You must login to create or update your blogs.')
        return redirect('account:login')

    if request.method == 'POST':
        form = BlogForm(request.POST)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.user = user
            blog.save()
            form.save_m2m()

            messages.success(request, f'Blog created successfully.')
            return redirect('blog:blog-detail', blog_id = blog.id)
        else:
            context['form'] = form

    if request.method == 'GET':
        form = BlogForm()
        context['form'] = form
    return render(request, 'blog/blog_add.html', context)


def blog_detail_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(
            request, 'You must login to view blogs or posts.')
        return redirect('account:login')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        messages.warning(request, 'Sorry!, blog not available.')
        return redirect('home')

    context['blog'] = blog
    return render(request, 'blog/blog_detail.html', context)


def blog_edit_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        messages.warning(
            request, 'You must login to create or update your blogs or posts.')
        return redirect('account:login')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        messages.warning(request, 'Sorry!, blog not available.')
        return redirect('home')

    context['blog'] = blog

    if not blog.user == request.user:
        messages.warning(request, 'You cannot edit other persons blog.')
        return redirect('home')

    return render(request, 'blog/blog_edit.html', context)


def blog_update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to create or update your blogs or posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, blog not available.</div>')

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons blog.</div>')

    if request.method == "GET":
        form = BlogForm(instance=blog)
        context['blog'] = blog
        context['form'] = form
        return render(request, 'blog/snippets/blog_form.html', context)

    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        if form.is_valid():
            form.save()
            context['blog'] = blog
            return render(request, 'blog/snippets/blog.html', context)
        else:
            context['form'] = form
            context['blog'] = blog
            return render(request, 'blog/snippets/blog_form.html', context)


def blog_delete_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to delete your blogs or posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, blog not available.</div>')

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot delete other persons blog.</div>')

    if request.method == 'POST':
        blog.delete()
        messages.success(request, 'Blog deleted successfully.')
        return redirect('home')

    if request.method == 'GET':
        context['blog'] = blog

    return render(request, 'blog/blog_delete.html', context)


def post_add_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to add posts.</div>')

    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if not blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons blog.</div>')

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.blog = blog
            post.save()
            context['post'] = post
            return render(request, 'blog/snippets/post.html', context)
        else:
            context['form'] = form
            context['post'] = {'id': 'id-temp'} 
            return render(request, 'blog/snippets/post_add_form.html', context)

    if request.method == 'GET':
        form = PostForm()
        context['form'] = form
        context['blog'] = blog
        context['post'] = {'id': 'id-temp'}
    return render(request, 'blog/snippets/post_add_form.html', context)


def post_update_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to create or update your blogs or posts.</div>')

    post_id = kwargs.get('post_id')
    post = get_post_by_id(post_id)

    if not post:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, post not available.</div>')

    if not post.blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot update other persons post.</div>')

    if request.method == "GET":
        form = PostForm(instance=post)
        context['post'] = post
        context['form'] = form
        return render(request, 'blog/snippets/post_form.html', context)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            context['post'] = post
            return render(request, 'blog/snippets/post.html', context)
        else:
            context['post'] = post
            context['form'] = form
            return render(request, 'blog/snippets/post_form.html', context)


def post_delete_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to delete your blogs or posts.</div>')

    post_id = kwargs.get('post_id')
    post = get_post_by_id(post_id)

    if not post:
        return HttpResponse(f'<div class="alert alert-info">Sorry!, post not available.</div>')

    if not post.blog.user == request.user:
        return HttpResponse(f'<div class="alert alert-info">You cannot delete other persons post.</div>')

    post.delete()
    return HttpResponse()


def blog_like_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You cannot like a post unless you Login.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if blog:
        blog.like(user)

        context['blog'] = blog
    else:
        return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/blog_options.html', context)


def blog_dislike_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You cannot dislike a post unless you Login.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if blog:
        blog.dislike(user)

        context['blog'] = blog
    else:
        return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/blog_options.html', context)


def comment_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to comment on post.</div>')

    context = {}
    blog_id = kwargs.get('blog_id')
    blog = get_blog_by_id(blog_id)

    if request.method == 'POST':
        body = request.POST.get('comment-input', '')
        if blog:
            comment = Comment.objects.create(blog=blog, user=request.user, body=body)
            context['comment'] = comment
        else:
            return HttpResponse(f'<div class="alert alert-info">Invalid blog.</div>')

    return render(request, 'blog/snippets/comment.html', context)


def reply_view(request, *args, **kwargs):
    user = request.user
    if not user.is_authenticated:
        return HttpResponse(f'<div class="alert alert-info">You must login to reply on comment.</div>')

    context = {}
    comment_id = kwargs.get('comment_id')
    comment = get_comment_by_id(comment_id)

    if request.method == 'POST':

blogs/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 

from blog.models import Blog

def home(request, *args, **kwargs):
    context = {}

    blog_objects = Blog.objects.filter(status='1')

    paginator = Paginator(blog_objects, 5)
    page = request.GET.get('page')

    try:
        blogs = paginator.page(page)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)

    context ['blogs'] = blogs
    return render(request, 'home.html', context)

def page_not_found_view(request, *args, **kwargs):
    return render(request, '404.html', status=404)

templates/snippets/blog_elements.html
{% load temptags %}

{% include 'blog/snippets/blog_options.html' %}

{% if request.user.is_authenticated %}
<div class="d-flex border-top p-2 border-bottom">
    <form 
    id="comment-form" 
    class="inline-form" 
    hx-post="{% url 'blog:comment-blog' blog_id=blog.id %}"
        hx-target="#id-blog-comments-{{blog.id}}" 
        hx-swap="afterbegin"
        >
        <input class="comment-input" name="comment-input" type="text" placeholder="write your comment...">
    </form>
</div>

<div id="id-blog-comments-{{blog.id}}" class="d-flex flex-column flex-start p-2">
    {% for comment in blog.comments.all|sliceComment %}
    {% include 'blog/snippets/comment.html' %}
    {% endfor %}
</div>
{% endif %}

templates/snippets/blogs.html
{% if blogs %}
{% for blog in blogs %}
<div id="id-blog-{{blog.id}}" class="content-section mb-2 p-2">
    <div class="d-flex">
        <div class="container p-2 ml-2">
            <div class="d-flex border-bottom mb-2">
                <img src="{{ blog.user.display_pic.url }}" class="thumbnail">
                <a class="mx-2 pt-2" href="{% url 'accountProfile:get-user-blogs' account_id=blog.user.id %}">{{ blog.user.username }}</a>
            </div>
            <div class="py-2">
                <a class="d-flex" href="{% url 'blog:blog-detail' blog_id=blog.id %}">
                    <p class="mb-0"><strong>{{ blog.heading }}</strong></p>
                </a>
                <a class="d-flex" href="{% url 'blog:blog-detail' blog_id=blog.id %}">
                    <p class="mb-0">{{ blog.description }}</p>
                </a>
            </div>

            <div 
                id="id-blog-details-{{blog.id}}" 
                hx-trigger="every 60s"
                hx-get="{% url 'blog:get-blog-elements' blog_id=blog.id partial='True' %}"
                hx-target="#id-blog-details-{{blog.id}}" 
                hx-swap="innerHTML"
            >
                {% include 'snippets/blog_elements.html' %}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

templates/snippets/form.html
<!-- Base form style start -->
{% csrf_token %}
{% for error in form.non_field.errors %}
<small class="text-danger">{{ error }}</small>
{% endfor %}
{% for field in form.hidden_fields %}
{{ field }}
{% for error in field.errors %}
<small class="text-danger">{{ error }}</small>
{% endfor %}
{% endfor %}
{% for field in form.visible_fields %}
<div class="form-element">
{% if field.field.widget.input_type != "file" %}
{% if field.field.widget.input_type != "checkbox" %}
<label for="{{ field.id_for_label }}">{{ field.label }}</label>
{{ field }}
{% else %}
{{ field }}
<label for="{{ field.id_for_label }}">{{ field.label }}</label>
{% endif %}
{% if field.help_text %}
<div class="ml-2 mb-0"><small>{{ field.help_text }}</small></div>
{% endif %}
{% for error in field.errors %}
<small class="text-danger">{{ error }}</small>
{% endfor %}
{% endif %}
</div>
{% endfor %}
<hr class="mt-1 mb-2">
<!-- Base form style end -->

templates/snippets/navbar.html
<!-- Navbar Start -->

<style>
.navbar {
    padding: .25rem 2.5rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: var(--bg-primary);
    color: var(--font-color);
}

.brand-title {
    font-size: 1.75rem;
    font-weight: 700;
    padding: .25rem;
}

.brand-title a {
    text-decoration: none;
    color: var(--font-color);
    display: block;
}

.navbar-links {
    display: flex;
    justify-content: space-between;
}

.navbar-links ul {
    display: flex;
    margin: .25rem 0;
}

.navbar-links li {
    list-style: none;
	border-radius: 2px;
}

.navbar-links li a {
    text-decoration: none;
    color: var(--font-color);
    padding: .5rem 1rem;
    display: block;
}

.navbar-links li:hover {
    background-color: var(--bg-secondary);
}

.toggle-button {
    position: absolute;
    top: 1rem;
    right: 2rem;
    display: none;
    flex-direction: column;
    justify-content: space-between;
    width: 30px;
    height: 20px;
}

.toggle-button .bar {
    height: 4px;
    width: 100%;
    background-color: var(--font-color);
    border-radius: 5px;
}

.nav-input {
    width: 200px;
}

@media (max-width: 768px) {
    .toggle-button {
        display: flex;
    }

    .navbar-links {
        display: none;
        flex-direction: column;
        width: 100%;
    }

    .navbar {
        flex-direction: column;
        align-items: flex-start;
    }

    .navbar-links ul {
        width: 100%;
        flex-direction: column;
    }

    .navbar-links li {
        text-align: center;
    }

    .navbar-links li a {
        padding: .5rem 1rem;
    }

    .navbar-links.active {
        display: flex;
    }

    .nav-input {
        margin: .5rem 0;
    }
}

</style>
<nav class="navbar">
    <div class="brand-title"><a href="{% url 'home' %}">LOGO</a></div>
    <a href="#" class="toggle-button">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </a>
    <div class="navbar-links">
        <ul>
            <li><a href="#" id="toggle-theme">Dark Mode</a></li>
            <form class="d-flex mx-2" onsubmit="return executeQuery();">
                <input class="nav-input" type="text" placeholder="Search" name="userQuery" id="id_search">
            </form>
            {% if user.is_authenticated %}
            <li><a href="{% url 'account:account' user_id=request.user.id %}">Profile</a></li>
            <li><a href="{% url 'account:logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account:login' %}">Login</a></li>
            <li><a href="{% url 'account:register' %}">Register</a></li> 
            {% endif %}  
        </ul>
    </div>
</nav>

<script type="text/javascript">
    function executeQuery() {
        var query = ""
        query = document.getElementById('id_search').value;
        window.location.replace("{% url 'account:account-search' %}?userQuery=" + query)
        return false
    }
</script>

<script>
    const toggleBtn = document.getElementsByClassName("toggle-button")[0]
    const navbarLinks = document.getElementsByClassName("navbar-links")[0]

    toggleBtn.addEventListener("click", () => {
        navbarLinks.classList.toggle("active")
    })
</script>

<script>
    document.getElementById("toggle-theme").addEventListener("click", function(e) {
        const theme = localStorage.getItem("theme-mode")
        console.log(theme)
        if (theme === null) {
            localStorage.setItem("theme-mode", "dark")
            window.location.reload()    
        } else {
            localStorage.removeItem("theme-mode")
            window.location.reload()
        }
    })
</script>
<!-- Navbar Ends -->

templates/snippets/pagination.html
{% if blogs.has_other_pages %}

<div class="content-section mt-2">
    <div class="d-flex justify-content-center">
        {% if blogs.has_previous %}
        <a href="?page=1" class="btn bg-none hide-sm">&laquo; First</a>
        <a href="?page={{ blogs.previous_page_number }}" class="btn bg-none" role="button">Prev</a>
        {% else %}
        <a href="?page=1" class="btn bg-none hide-sm">&laquo; First</a>
        <a href="#" class="btn bg-none disabled" role="button">Prev</a>
        {% endif %}

        <span class="btn bg-none current mx-2">
            Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}
        </span>

        {% if blogs.has_next %}
        <a href="?page={{ blogs.next_page_number }}" class="btn bg-none" role="button">Next</a>
        <a href="?page={{ blogs.paginator.num_pages }}" class="btn bg-none hide-sm">Last &raquo;</a>
        {% else %}
        <a href="#" class="btn bg-none disabled" role="button">Next</a>
        <a href="?page={{ blogs.paginator.num_pages }}" class="btn bg-none hide-sm">Last &raquo;</a>
        {% endif %}
    </div>
</div>

<style>
    @media (max-width: 512px) {
        .hide-sm {
            display: none;
        }
    }
</style>

{% endif %}