blog/urls.py
from django.urls import path

from blog.views import (
    blog_create_view, 
    blog_detail_view, 
    blog_edit_view, 
    blog_delete_view,
    blog_update_view,

    post_add_view,
    post_update_view,
    post_delete_view,
    
    blog_like_view,
    blog_dislike_view,
    comment_view,
    reply_view,
    get_blog_elements_view,

    get_tags_view,
    add_tags_to_blog,
    remove_tags_from_blog,
    publish_blog_view,
)

app_name = 'blog'

urlpatterns = [
    path('blog_create', blog_create_view, name='blog-create'),
    path('blog_detail/<blog_id>/', blog_detail_view, name='blog-detail'),
    path('blog_edit/<blog_id>/', blog_edit_view, name='blog-edit'),
    path('blog-delete/<blog_id>/', blog_delete_view, name='blog-delete'),
    path('blog_update/<blog_id>/', blog_update_view, name='blog-update'),

    path('post_add/<blog_id>/', post_add_view, name='post-add'),
    path('post_update/<post_id>/', post_update_view, name='post-update'),
    path('post_delete/<post_id>/', post_delete_view, name='post-delete'),

    path('blog_like/<blog_id>/', blog_like_view, name='like-blog'),
    path('blog_dislike/<blog_id>/', blog_dislike_view, name='dislike-blog'),
    path('blog_comment/<blog_id>/', comment_view, name='comment-blog'),
    path('comment_reply/<comment_id>/', reply_view, name='reply-comment'),
    path('get_blog_elements/<blog_id>/', get_blog_elements_view, name='get-blog-elements'),
    path('get_blog_elements/<blog_id>/<partial>/',get_blog_elements_view, name='get-blog-elements'),

    path('get_tags/<blog_id>/', get_tags_view, name='get-tags'),
    path('add_tag_to_blog/<blog_id>/<tag_id>/', add_tags_to_blog, name='add-tag-to-blog'),
    path('remove_tag_from-blog/<blog_id>/<tag_id>/', remove_tags_from_blog, name='remove-tag-from-blog'),
    path('publish_blog/<blog_id>/', publish_blog_view, name='publish-blog'),
]

blogs/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from blogs.views import home


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    
    path('', include('account.urls', namespace='account')),
    path('api/', include('account.api.urls', namespace='account_api')),

    path('', include('accountProfile.urls', namespace='accountProfile')),

    path('', include('blog.urls', namespace='blog')),
]

handler404 = 'blogs.views.page_not_found_view'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">

    <script src="https://www.google.com/recaptcha/api.js" async defer></script>

    <title>Base</title>
</head>
<body>

    {% include 'snippets/navbar.html' %}

    <div class="d-flex flex-column pt-2 px-4 mx-auto">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} my-1 mx-auto">
            {{ message|safe }}
        </div>
        {% endfor %}
        {% endif %}

        {% block message %}{% endblock message %}
    </div>
    
    <main>
        {% block content %}{% endblock content %}
        <div class="sidebar">
            <div class="content-section">
                <p class="m-0 pb-2 border-bottom">Themes</p>
                <div class="mt-2 p-0">
                    <button class="btn mx-1 theme-picker theme-picker-light"></button>
                    <button class="btn mx-1 theme-picker theme-picker-dark"></button>
                </div>
            </div>
            {% block sidebar_extension%}{% endblock sidebar_extension%}
        </div>
    </main>

    <script>
        function setTheme() {
            const theme = localStorage.getItem("theme-mode")
            if (theme !== null) {
                if (theme === 'dark') {
                    document.getElementById("toggle-theme").innerText = "Light Mode"
                    document.body.setAttribute('data-theme', 'dark')
                }
            }
        }
        setTheme()

        document.getElementsByClassName('theme-picker-light')[0].addEventListener('click', () => {
            localStorage.removeItem("theme-mode")
            window.location.reload()
        })

        document.getElementsByClassName('theme-picker-dark')[0].addEventListener('click', () => {
            localStorage.setItem("theme-mode", "dark")
            window.location.reload() 
        })

        // function getToken(name) {
        //     var cookieValue = null;
        //     if (document.cookie && document.cookie !== '') {
        //         var cookies = document.cookie.split(';');
        //         for (var i = 0; i < cookies.length; i++) {
        //             var cookie = cookies[i].trim();
        //             // Does this cookie string begin with the name we want?
        //             if (cookie.substring(0, name.length + 1) === (name + '=')) {
        //                 cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
        //                 break;
        //             }
        //         }
        //     }
        //     return cookieValue;
        // }
        // const csrf_token = getToken('csrftoken')
    </script>
    
    <script src="https://unpkg.com/htmx.org@1.7.0"
        integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous"
        defer>
    </script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% load temptags %}

{% block content %}
<div class="container">
    {% if request.user.is_authenticated %}
    <div class="content-section mb-2 p-2">
        <div id="id-home-header" class="p-2">
            <a href="{% url 'blog:blog-create' %}" class="btn btn-outline-info">Add New Blog</a>
            {% if request.user.is_authenticated %}
            <button
                id="id_tag_btn"
                class="btn btn-outline-info"
                hx-trigger="click" 
                hx-get="{% url 'accountProfile:get-tags' %}"
                hx-target="#id-home-header" 
                hx-swap="beforeend"
                >
                Tags
            </button>
            {% endif %}
        </div>
    </div>
    {% endif %}
    {% include 'snippets/blogs.html' %}
    {% include 'snippets/pagination.html' %}
</div>

<script>
    document.body.addEventListener("htmx:configRequest", (event) => {
        event.detail.headers["X-CSRFToken"] = "{{ csrf_token }}"
    })

    document.body.addEventListener("htmx:afterRequest", (event) => {
        let commentInputs = document.querySelectorAll("input.comment-input")
        commentInputs.forEach((comment) => {
            comment.value = ""
        })

        let replyInputs = document.querySelectorAll("input.reply-input")
        replyInputs.forEach((reply) => {
            reply.value = ""
        })
    })

    const showReplyForm = (commentId) => {
        event.preventDefault()
        document.getElementById(`id-reply-btn-${commentId}`).classList.add("d-none")
        document.getElementById(`id-reply-form-${commentId}`).classList.remove("d-none")
    }

    document.getElementById('id_tag_btn').addEventListener('click', async (e) => {
        e.preventDefault()
        await delay(1000)
        document.getElementById('id_tag_btn').remove()
    })

    function delay(milliseconds) {
        return new Promise(resolve => {
            setTimeout(resolve, milliseconds);
        });
    }
</script>

{% endblock content %}